version: '3'
services:
  kong:
    image: kong:latest
    container_name: kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - database
    networks:
      - kong_network
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
      - ./api-token:/usr/local/bin/api-token
    command: kong start
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PLUGINS=api-token,jwt  
      - KONG_PLUGINSERVER_NAMES=api-token
      - KONG_PLUGINSERVER_API_TOKEN_QUERY_CMD=/usr/local/bin/api-token -dump
      - KONG_LOG_LEVEL=info
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
     
    

  konga:
    image: pantsel/konga:latest
    container_name: konga
    environment:
      TOKEN_SECRET: "your_token_secret"
      NODE_ENV: "production"
    ports:
      - "1337:1337"
    depends_on:
      - database
    networks:
      - kong_network

  database:
    image: postgres:alpine
    container_name: kong_database
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "kong"
    ports:
      - "5432:5432"
    networks:
      - kong_network

networks:
  kong_network:
    driver: bridge
